version: "3.2"
services:
  rapid:
    stdin_open: true
    tty: true
    container_name: hiwat_rapid
    image: byu_hydro/hiwat_rapid
    build:
      context: ./
    volumes:
      - type: bind
        source: ./input_data
        target: /home/rapid-io/input
      - type: bind
        source: ./output_files
        target: /home/rapid-io/output
      - type: bind
        source: ./input_dataset
        target: /home/input_dataset
      - type: bind
        source: ./run_script.py
        target: /home/run_script.py

