version: "3.2"
services:
  rapid:
    environment:
      - REGION=south_asia-geoglows
      - SERVICE=aws
    stdin_open: true
    tty: true
    container_name: rapid
    image: spt_compute_docker
    build:
      context: ./
    volumes:
      - type: bind
        source: ./input_data
        target: /home/rapid-io/input
      - type: bind
        source: ./ecmwf_data
        target: /home/ecmwf_data
      - type: bind
        source: ./run_logs
        target: /home/logs
      - type: bind
        source: ./subprocess_logs
        target: /home/subprocess_logs
      - type: bind
        source: ./output_files
        target: /home/rapid-io/output
      - type: bind
        source: ./scripts
        target: /home/scripts